export type CustomerOverviewProfile = {
  name: string
  badge: string
  industry: string
  businessUnit: string
  accountManager: string
  customerId: string
  relationshipSince: string
  gstin: string
}

export const customerOverviewProfile: CustomerOverviewProfile = {
  name: 'ABC Industries Pvt. Ltd.',
  badge: 'Strategic Customer',
  industry: 'Manufacturing',
  businessUnit: 'Industrial Supplies',
  accountManager: 'Ramesh N.',
  customerId: 'CUST-000345',
  relationshipSince: 'Aug 2019',
  gstin: '29AACCA1234A1Z5',
}

export const customerOverviewStats = {
  annualRevenueContribution: '₹8.75 Cr',
  annualRevenueContributionSublabel: '8.2% of total revenue',
  currentCreditLimit: '₹2.50 Cr',
  outstandingBalance: '₹1.28 Cr',
  availableCredit: '₹1.22 Cr',
  lastPaymentReceived: '₹24.60 L',
  lastPaymentReceivedDate: 'on 12 May 2025',
}

export const financialHealth = {
  score: 82,
  status: 'Healthy' as const,
  creditUtilization: 51,
  collectionEfficiency: 91,
  dsoDays: 35,
  paymentDiscipline: 'Good',
  revenueTrendYoY: 12,
  revenueTrendPoints: [38, 42, 40, 46, 50, 48, 54, 58, 55, 60, 64, 68],
  cashContribution: '₹6.45 Cr',
  profitabilityIndicator: 'High',
}

export const riskAssessment = {
  riskLevel: 'Low Risk' as const,
  aiRiskScore: 28,
  defaultProbability: '6%',
  latePaymentTrend3M: 'Improving',
  creditExposure: '₹1.28 Cr',
  disputeHistoryAmount: '₹0',
  disputeHistoryOpenCount: 0,
  externalMarketRisk: 'Low',
}

export const businessRelationship = {
  totalBusinessValue: '₹18.40 Cr',
  totalInvoicesRaised: 236,
  totalCollections: '₹17.12 Cr',
  activeContracts: 2,
  productsServices: 24,
  avgMonthlyBilling: '₹72.30 L',
  customerLifetimeValue: '₹24.80 Cr',
}

export type PaymentBehaviorBucket = 'On-time' | '1-15 Days Late' | '16-30 Days Late' | '30+ Days Late' | 'No Payment'

export const paymentBehaviorMonths = [
  'Jun \'24', 'Jul \'24', 'Aug \'24', 'Sep \'24', 'Oct \'24', 'Nov \'24',
  'Dec \'24', 'Jan \'25', 'Feb \'25', 'Mar \'25', 'Apr \'25', 'May \'25',
]

export const paymentBehaviorHeatMap: Record<PaymentBehaviorBucket, number[]> = {
  'On-time': [18, 22, 20, 24, 23, 25, 27, 24, 26, 28, 27, 24],
  '1-15 Days Late': [9, 8, 10, 9, 11, 8, 9, 10, 9, 8, 7, 9],
  '16-30 Days Late': [4, 5, 3, 4, 3, 5, 3, 4, 4, 3, 4, 3],
  '30+ Days Late': [2, 2, 3, 2, 1, 2, 1, 2, 1, 2, 2, 1],
  'No Payment': [1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1],
}

export const paymentBehaviorStats = {
  onTimePayments: 62,
  onTimePaymentsDelta: '8% vs prev 12M',
  avgDelayDays: 11,
  avgDelayDaysDelta: '2 days vs prev 12M',
  maxDelayDays: 38,
  maxDelayDaysDelta: '5 days vs prev 12M',
  totalPayments: 312,
  totalPaymentsSublabel: 'Invoices Paid',
  paymentTrendLabel: 'Improving',
  paymentTrendPoints: [4, 6, 5, 7, 6, 8, 7, 9, 8, 10, 9, 11],
}

export const aiExecutiveSummary = {
  paragraphs: [
    'ABC Industries has been a customer since 2019 and contributes 8.2% of annual revenue. Payment performance has improved over the past three months, reducing the average payment cycle from 41 days to 35 days.',
    'The customer currently has ₹1.28 Cr in outstanding receivables with a 94% probability of paying within the next seven days.',
    'Overall financial health is Healthy, and the current credit policy is recommended to continue.',
  ],
  generatedBy: 'Generated by FinPilot AI',
  generatedAt: '18 May 2025, 09:30 AM',
}

export type RecommendedAction = {
  id: string
  title: string
  subtitle: string
  icon: 'credit' | 'monitor' | 'follow-up' | 'discount'
}

export const recommendedActions: RecommendedAction[] = [
  { id: 'credit-limit', title: 'Maintain current credit limit', subtitle: 'Customer is performing well within credit terms', icon: 'credit' },
  { id: 'monitor-invoices', title: 'Monitor high value invoices', subtitle: '2 invoices worth ₹68.40 L due in next 7 days', icon: 'monitor' },
  { id: 'follow-up', title: 'Continue regular follow-ups', subtitle: 'Payment trend is positive', icon: 'follow-up' },
  { id: 'discount', title: 'Offer early payment discount', subtitle: 'Customer responds well to early payment offers', icon: 'discount' },
]
